export const assessmentQuestions = [
  {
    id: "personal-interests",
    name: "الميول الشخصية",
    nameEn: "Personal Interests",
    description: "أسئلة تساعدنا في فهم اهتماماتك وميولك الشخصية",
    descriptionEn: "Questions to help us understand your personal interests and passions",
    icon: "heart",
    questions: [
      {
        id: "pi-1",
        text: "ما الذي تفضل القيام به في وقت فراغك؟",
        textEn: "What do you prefer to do in your free time?",
        category: "personal-interests",
        options: [
          { id: "pi-1-a", text: "القراءة والبحث عن مواضيع جديدة", textEn: "Reading and exploring new topics", value: 1 },
          { id: "pi-1-b", text: "تصميم وابتكار أشياء جديدة", textEn: "Designing and creating new things", value: 2 },
          { id: "pi-1-c", text: "التفاعل مع الناس ومساعدتهم", textEn: "Interacting with people and helping them", value: 3 },
          { id: "pi-1-d", text: "تحليل الأرقام وحل المسائل", textEn: "Analyzing numbers and solving problems", value: 4 },
          { id: "pi-1-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "pi-2",
        text: "أي نوع من المحتوى تستمتع به أكثر؟",
        textEn: "What type of content do you enjoy the most?",
        category: "personal-interests",
        options: [
          { id: "pi-2-a", text: "مقالات علمية وتقنية", textEn: "Scientific and technical articles", value: 1 },
          { id: "pi-2-b", text: "أعمال أدبية وفنية", textEn: "Literary and artistic works", value: 2 },
          { id: "pi-2-c", text: "محتوى تطوير الذات والقيادة", textEn: "Self-development and leadership content", value: 3 },
          { id: "pi-2-d", text: "الأخبار الاقتصادية والتجارية", textEn: "Business and economic news", value: 4 },
          { id: "pi-2-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "pi-3",
        text: "ما المشروع الذي تحلم بتنفيذه؟",
        textEn: "What kind of project do you dream of building?",
        category: "personal-interests",
        options: [
          { id: "pi-3-a", text: "تطوير تطبيق أو موقع إلكتروني", textEn: "Developing an app or website", value: 1 },
          { id: "pi-3-b", text: "إنشاء مشروع فني أو إبداعي", textEn: "Creating an artistic or creative project", value: 2 },
          { id: "pi-3-c", text: "تأسيس مؤسسة خيرية أو اجتماعية", textEn: "Founding a charity or social organization", value: 3 },
          { id: "pi-3-d", text: "بناء شركة تجارية ناجحة", textEn: "Building a successful business", value: 4 },
          { id: "pi-3-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "pi-4",
        text: "ما الذي يجذب انتباهك أكثر في الأخبار؟",
        textEn: "What type of news catches your attention the most?",
        category: "personal-interests",
        options: [
          { id: "pi-4-a", text: "الاكتشافات العلمية والتقنية", textEn: "Scientific and tech discoveries", value: 1 },
          { id: "pi-4-b", text: "الأحداث الثقافية والفنية", textEn: "Cultural and artistic events", value: 2 },
          { id: "pi-4-c", text: "القضايا الاجتماعية والإنسانية", textEn: "Social and humanitarian issues", value: 3 },
          { id: "pi-4-d", text: "أخبار الاقتصاد والأعمال", textEn: "Economy and business news", value: 4 },
          { id: "pi-4-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
    ],
  },
  {
    id: "academic-abilities",
    name: "القدرات الأكاديمية",
    nameEn: "Academic Abilities",
    description: "أسئلة تقيّم قدراتك الأكاديمية في مختلف المجالات",
    descriptionEn: "Questions that evaluate your academic strengths across different fields",
    icon: "book",
    questions: [
      {
        id: "aa-1",
        text: "ما المادة الدراسية التي تتفوق فيها أكثر؟",
        textEn: "Which subject do you excel in the most?",
        category: "academic-abilities",
        options: [
          { id: "aa-1-a", text: "الرياضيات والفيزياء", textEn: "Mathematics and Physics", value: 1 },
          { id: "aa-1-b", text: "اللغات والأدب", textEn: "Languages and Literature", value: 2 },
          { id: "aa-1-c", text: "العلوم الاجتماعية والتاريخ", textEn: "Social Studies and History", value: 3 },
          { id: "aa-1-d", text: "الأحياء والكيمياء", textEn: "Biology and Chemistry", value: 4 },
          { id: "aa-1-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "aa-2",
        text: "كيف تصف أسلوبك في التعلم؟",
        textEn: "How would you describe your learning style?",
        category: "academic-abilities",
        options: [
          { id: "aa-2-a", text: "التعلم العملي والتجريبي (أتعلم بالممارسة)", textEn: "Hands-on and practical learning", value: 1 },
          { id: "aa-2-b", text: "القراءة والكتابة والبحث", textEn: "Reading, writing, and research", value: 2 },
          { id: "aa-2-c", text: "المناقشة والتعلم الجماعي", textEn: "Discussion and collaborative learning", value: 3 },
          { id: "aa-2-d", text: "المشاهدة والتحليل البصري", textEn: "Visual learning and analysis", value: 4 },
          { id: "aa-2-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "aa-3",
        text: "ما نوع المشاريع الدراسية التي تستمتع بها؟",
        textEn: "What type of academic projects do you enjoy?",
        category: "academic-abilities",
        options: [
          { id: "aa-3-a", text: "مشاريع برمجية وتقنية", textEn: "Programming and technical projects", value: 1 },
          { id: "aa-3-b", text: "مشاريع بحثية وكتابية", textEn: "Research and writing projects", value: 2 },
          { id: "aa-3-c", text: "عروض تقديمية ومناقشات جماعية", textEn: "Presentations and group discussions", value: 3 },
          { id: "aa-3-d", text: "تجارب معملية وعلمية", textEn: "Lab experiments and scientific work", value: 4 },
          { id: "aa-3-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "aa-4",
        text: "كيف تتعامل مع المشكلات الصعبة؟",
        textEn: "How do you approach difficult problems?",
        category: "academic-abilities",
        options: [
          { id: "aa-4-a", text: "أحللها منطقياً خطوة بخطوة", textEn: "I analyze them logically step by step", value: 1 },
          { id: "aa-4-b", text: "أبحث عن حلول إبداعية وغير تقليدية", textEn: "I look for creative and unconventional solutions", value: 2 },
          { id: "aa-4-c", text: "أستشير الآخرين وأعمل معهم", textEn: "I consult others and collaborate", value: 3 },
          { id: "aa-4-d", text: "أبحث وأقرأ حتى أجد الحل", textEn: "I research and read until I find a solution", value: 4 },
          { id: "aa-4-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
    ],
  },
  {
    id: "personal-skills",
    name: "المهارات الشخصية",
    nameEn: "Personal Skills",
    description: "أسئلة تكشف عن مهاراتك الشخصية وقدراتك الاجتماعية",
    descriptionEn: "Questions that reveal your personal strengths and social abilities",
    icon: "star",
    questions: [
      {
        id: "ps-1",
        text: "كيف تصف نفسك في بيئة العمل الجماعي؟",
        textEn: "How would you describe yourself in a team setting?",
        category: "personal-skills",
        options: [
          { id: "ps-1-a", text: "القائد الذي ينظم ويوجه الفريق", textEn: "The leader who organizes and guides the team", value: 1 },
          { id: "ps-1-b", text: "المبدع الذي يقدم أفكاراً خلّاقة", textEn: "The creative one who generates new ideas", value: 2 },
          { id: "ps-1-c", text: "المنفذ الدقيق الذي ينجز المهام", textEn: "The detail-oriented executor who gets things done", value: 3 },
          { id: "ps-1-d", text: "الوسيط الذي يوحد الفريق ويحل الخلافات", textEn: "The mediator who unites the team and resolves conflicts", value: 4 },
          { id: "ps-1-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "ps-2",
        text: "ما المهارة التي تعتبرها الأقوى لديك؟",
        textEn: "Which skill do you consider your strongest?",
        category: "personal-skills",
        options: [
          { id: "ps-2-a", text: "التواصل والإقناع", textEn: "Communication and persuasion", value: 1 },
          { id: "ps-2-b", text: "التحليل والتفكير النقدي", textEn: "Analysis and critical thinking", value: 2 },
          { id: "ps-2-c", text: "الإبداع والابتكار", textEn: "Creativity and innovation", value: 3 },
          { id: "ps-2-d", text: "التنظيم وإدارة الوقت", textEn: "Organization and time management", value: 4 },
          { id: "ps-2-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "ps-3",
        text: "كيف تتعامل مع الضغوط والتحديات؟",
        textEn: "How do you handle pressure and challenges?",
        category: "personal-skills",
        options: [
          { id: "ps-3-a", text: "أواجهها بثقة وأحولها لفرص", textEn: "I face them confidently and turn them into opportunities", value: 1 },
          { id: "ps-3-b", text: "أخطط وأنظم أولوياتي بعناية", textEn: "I plan carefully and organize my priorities", value: 2 },
          { id: "ps-3-c", text: "أطلب الدعم وأتعاون مع الآخرين", textEn: "I seek support and collaborate with others", value: 3 },
          { id: "ps-3-d", text: "أتأمل وأفكر بعمق قبل القرار", textEn: "I reflect deeply before making decisions", value: 4 },
          { id: "ps-3-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "ps-4",
        text: "ما الدور الذي تفضله في المجتمع؟",
        textEn: "What role do you prefer to play in society?",
        category: "personal-skills",
        options: [
          { id: "ps-4-a", text: "معلم أو مرشد يوجه الآخرين", textEn: "A teacher or mentor who guides others", value: 1 },
          { id: "ps-4-b", text: "مبتكر يصنع حلولاً لمشكلات قائمة", textEn: "An innovator who creates solutions to real problems", value: 2 },
          { id: "ps-4-c", text: "قائد يدير المؤسسات ويطورها", textEn: "A leader who manages and develops organizations", value: 3 },
          { id: "ps-4-d", text: "باحث يكتشف المعرفة ويوثقها", textEn: "A researcher who discovers and documents knowledge", value: 4 },
          { id: "ps-4-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
    ],
  },
  {
    id: "career-preferences",
    name: "التفضيلات المهنية",
    nameEn: "Career Preferences",
    description: "أسئلة تحدد تفضيلاتك المهنية وبيئة العمل المثالية لك",
    descriptionEn: "Questions that define your career preferences and ideal work environment",
    icon: "briefcase",
    questions: [
      {
        id: "cp-1",
        text: "ما بيئة العمل التي تناسبك أكثر؟",
        textEn: "Which work environment suits you best?",
        category: "career-preferences",
        options: [
          { id: "cp-1-a", text: "مكتب تقني أو شركة ناشئة", textEn: "Tech office or startup", value: 1 },
          { id: "cp-1-b", text: "استوديو إبداعي أو وكالة تصميم", textEn: "Creative studio or design agency", value: 2 },
          { id: "cp-1-c", text: "مستشفى أو مؤسسة صحية أو تعليمية", textEn: "Hospital, healthcare or educational institution", value: 3 },
          { id: "cp-1-d", text: "شركة أعمال أو بنك أو مؤسسة حكومية", textEn: "Business, bank, or government institution", value: 4 },
          { id: "cp-1-e", text: "العمل الحر عن بُعد (فريلانس)", textEn: "Remote freelance work", value: 5 },
          { id: "cp-1-f", text: "ميدان أو بيئة متنوعة (عمل خارجي)", textEn: "Field or varied environment (outdoor work)", value: 6 },
          { id: "cp-1-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "cp-2",
        text: "ما الأهم بالنسبة لك في مسارك المستقبلي؟",
        textEn: "What matters most to you in your future career?",
        category: "career-preferences",
        options: [
          { id: "cp-2-a", text: "الدخل المرتفع والاستقرار المالي", textEn: "High income and financial stability", value: 1 },
          { id: "cp-2-b", text: "الإبداع والحرية في التعبير", textEn: "Creativity and freedom of expression", value: 2 },
          { id: "cp-2-c", text: "خدمة المجتمع والتأثير الإيجابي", textEn: "Community service and positive impact", value: 3 },
          { id: "cp-2-d", text: "التطوير المستمر وفرص الترقي", textEn: "Continuous growth and promotion opportunities", value: 4 },
          { id: "cp-2-e", text: "التوازن بين العمل والحياة الشخصية", textEn: "Work-life balance", value: 5 },
          { id: "cp-2-f", text: "ريادة الأعمال والاستقلالية", textEn: "Entrepreneurship and independence", value: 6 },
          { id: "cp-2-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
      {
        id: "cp-3",
        text: "ما خططك المستقبلية؟",
        textEn: "What are your future plans?",
        category: "career-preferences",
        options: [
          { id: "cp-3-a", text: "الدراسة الجامعية في بلدي", textEn: "University study in my country", value: 1 },
          { id: "cp-3-b", text: "الدراسة الجامعية في الخارج", textEn: "University study abroad", value: 2 },
          { id: "cp-3-c", text: "الدخول لسوق العمل مباشرة", textEn: "Enter the job market directly", value: 3 },
          { id: "cp-3-d", text: "الجمع بين الدراسة والعمل", textEn: "Combine study and work", value: 4 },
          { id: "cp-3-e", text: "تأسيس مشروعي الخاص", textEn: "Start my own business", value: 5 },
          { id: "cp-3-other", text: "لم أقرر بعد", textEn: "I haven't decided yet", value: 0 },
        ],
      },
      {
        id: "cp-4",
        text: "ما القطاع الذي تراه الأكثر جاذبية؟",
        textEn: "Which sector do you find most appealing?",
        category: "career-preferences",
        options: [
          { id: "cp-4-a", text: "التكنولوجيا والذكاء الاصطناعي", textEn: "Technology and AI", value: 1 },
          { id: "cp-4-b", text: "الطب والصحة والعلوم الحيوية", textEn: "Medicine, health, and life sciences", value: 2 },
          { id: "cp-4-c", text: "التعليم والتدريب والإرشاد", textEn: "Education, training, and coaching", value: 3 },
          { id: "cp-4-d", text: "الأعمال والمال وريادة الأعمال", textEn: "Business, finance, and entrepreneurship", value: 4 },
          { id: "cp-4-e", text: "الهندسة والبناء والبنية التحتية", textEn: "Engineering, construction, and infrastructure", value: 5 },
          { id: "cp-4-f", text: "الإعلام والتسويق والفنون الرقمية", textEn: "Media, marketing, and digital arts", value: 6 },
          { id: "cp-4-g", text: "القانون والشؤون الاجتماعية والسياسة", textEn: "Law, social affairs, and politics", value: 7 },
          { id: "cp-4-other", text: "غير ذلك", textEn: "Other", value: 0 },
        ],
      },
    ],
  },
];
